solutions/w4/w4d3/cats99/config/routes.rb
Cats99::Application.routes.draw do
  resources :cats do
    resources :cat_rental_requests
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: "cats#index"
end

solutions/w4/w4d3/cats99/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["Red", "Black", "White", "Blue", "Other"]

  attr_accessible :birthday, :color, :name, :user_id, :sex

  belongs_to :user
  has_many :cat_rental_requests, dependent: :destroy

  validates :birthday, :name, :user, presence: true
  validates :color, presence: true, inclusion: { :in => COLORS }
  validates :sex, presence: true, inclusion: { :in => ["Male", "Female"] }
end

solutions/w4/w4d3/cats99/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :begin_date, :cat_id, :end_date, :status

  belongs_to :cat

  default_scope order('begin_date ASC')

  validates :begin_date, :end_date, :cat, presence: true
  validates :status, presence: true, 
    inclusion: { :in => ["undecided", "approved", "denied"] }
  validate :end_after_begin, :dates_not_overlap

  def approve
    self.status = 'approved'
    save
    overlapping_requests.update_all({status: "denied"}, "status = 'undecided'")
  end

  private

  def end_after_begin
    unless end_date > begin_date
      errors[:end_date] << "must be after the begin date"
    end
  end

  def dates_not_overlap
    if approved_overlapping_requests.count > 0
      errors[:begin_date] << "overlaps an existing approved request"
      errors[:end_date] << "overlaps an existing approved request"
    end
  end

  def overlapping_requests
    CatRentalRequest.where(cat_id: cat_id).
      where("NOT (begin_date > ? OR end_date < ?)", end_date, begin_date)
  end

  def approved_overlapping_requests
    overlapping_requests.where(status: "approved")
  end
end

solutions/w4/w4d3/cats99/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :session_token, :username

  has_many :cats

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

solutions/w4/w4d3/cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery

  def authenticate_user!
    redirect_to new_session_path unless logged_in?
  end
end

solutions/w4/w4d3/cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user!, only: [:update]

  def new
    @cat = Cat.find(params[:cat_id])
    @request = CatRentalRequest.new
  end

  def create
    @cat = Cat.find(params[:cat_id])
    @request = @cat.cat_rental_requests.build(params[:cat_rental_request])
    if @request.save
      redirect_to @cat
    else
      render :new
    end
  end

  def update
    @cat = Cat.find(params[:cat_id])
    req = CatRentalRequest.find(params[:id])
    if params[:cat_rental_request][:status] && 
      params[:cat_rental_request][:status] == "approved"
        req.approve
    else
      req.update_attributes(params[:cat_rental_request])
    end
    redirect_to @cat
  end

  def authorize_user!
    cat = Cat.find(params[:cat_id])
    unless current_user == cat.user
      flash[:error] = "Only the owner of the cat can do this."
      redirect_to cat
    end
  end
end

solutions/w4/w4d3/cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = current_user.cats.build(params[:cat])
    if @cat.save
      redirect_to @cat
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(params[:cat])
      redirect_to @cat
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_path
  end

  private

  def authorize_user!
    cat = Cat.find(params[:id])
    unless current_user == cat.user
      flash[:error] = "Only the owner of the cat can do this."
      redirect_to cat
    end
  end
end

solutions/w4/w4d3/cats99/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.password == params[:password]
      login(user)
      redirect_to cats_path
    else
      flash.now[:error] = "Invalid login. Please try again."
      render :new
    end
  end

  def destroy
    logout
    redirect_to :back
  end
end

solutions/w4/w4d3/cats99/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login(@user)
      redirect_to cats_path
    else
      render :new
    end
  end
end

solutions/w4/w4d3/cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

solutions/w4/w4d3/cats99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

solutions/w4/w4d3/cats99/app/helpers/cats_helper.rb
module CatsHelper
end

solutions/w4/w4d3/cats99/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user.session_token = generate_unique_random_token
    user.save!
    session[:token] = user.session_token
  end

  def logout
    session[:token] = nil
  end

  def generate_unique_random_token
    token = SecureRandom.urlsafe_base64
    while User.find_by_session_token(token)
      token = SecureRandom.urlsafe_base64
    end
    token
  end
end

solutions/w4/w4d3/cats99/app/helpers/users_helper.rb
module UsersHelper
end

solutions/w4/w4d3/cats99/app/views/cat_rental_requests/new.html.erb
<h3>New Cat Rental Request <small>(<%= @cat.name %>)</small></h3>

<% @request.errors.full_messages.each do |error| %>
  <p style='color: red;'><b><%= error %></b></p>
<% end %>

<%= form_for([@cat, @request]) do %>
  <label for="request_begin_date">Begin</label>
  <input type='date' id='request_begin_date' 
    name='cat_rental_request[begin_date]' value='<%= @request.begin_date %>'>
  <br>
  <label for="request_end_date">End</label>
  <input type='date' id='request_end_date' 
    name='cat_rental_request[end_date]' value='<%= @request.end_date %>'>
  <br>
  <input type='submit'>
<% end %>

solutions/w4/w4d3/cats99/app/views/cats/_form.html.erb
<% @cat.errors.full_messages.each do |error| %>
  <p style='color: red;'><b><%= error %></b></p>
<% end %>

<%= form_for(@cat) do %>
  <label for='cat_name'>Name</label>
  <input type='text' name='cat[name]' id='cat_name' value='<%= @cat.name %>'>
  <br>
  <label for='cat_color'>Color</label>
  <select name='cat[color]'>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= "selected" if color == @cat.color %>>
        <%= color %>
      </option>
    <% end %>
  </select>
  <br>
  <label for='cat_sex'>Sex</label>
    <% ["Male", "Female"].each do |sex| %>
      <label>
        <input type="radio" name="cat[sex]" 
          value="<%= sex %>" <%= "checked" if sex == @cat.sex %>>
        <%= sex %>
      </label>
    <% end %>
  <br>
  <label for='cat_birthday'>Birthday</label>
  <input type='date' name='cat[birthday]' id='cat_birthday' 
    value='<%= @cat.birthday %>' >
  <br>

  <input type='submit'>
<% end %>

solutions/w4/w4d3/cats99/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render :partial => "form" %>

solutions/w4/w4d3/cats99/app/views/cats/index.html.erb
<h3>Index</h3>

<% if @cats.length > 0 %>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= link_to cat.name, cat_path(cat) %>
    </li>
  <% end %>
</ul>

<% else %>

<p>No cats yet...</p>

<% end %>

<% if logged_in? %>
  <%= link_to "+ New Cat", new_cat_path %>
<% end %>

solutions/w4/w4d3/cats99/app/views/cats/new.html.erb
<h3>New Cat</h3>

<%= render :partial => "form" %>

solutions/w4/w4d3/cats99/app/views/cats/show.html.erb
<h3>
  <%= @cat.name %>
  <small>
    <% if logged_in? && current_user.id == @cat.user_id %>
      <%= link_to "edit", edit_cat_path(@cat) %>
    <% end %>
  </small>
</h3>

<pre>
  <%= @cat.inspect %>
</pre>

<h4>Requests</h4>
<% if @cat.cat_rental_requests.count > 0 %>
  <ol>
  <% @cat.cat_rental_requests.each do |req| %>
    <li>
      <%= req.begin_date %> -> <%= req.end_date %> (<b><%= req.status %></b>)
      <% if logged_in? && current_user == @cat.user && req.status == "undecided" %>
        <% [["Approve", "approved"],["Deny", "denied"]].each do |action, value| %>
          <%= form_for([@cat, req], html: {style: "display: inline;"}) do %>
            <input type='hidden' name='cat_rental_request[status]' 
              value='<%= value %>'>
            <input type='submit' value='<%= action %>'>
          <% end %>
        <% end %>
      <% end %>
    </li>
  <% end %>
  </ol>
<% else %>
  <p>No requests yet...</p>
<% end %>
<%= link_to "+ New Request", new_cat_cat_rental_request_path(@cat) %>

solutions/w4/w4d3/cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>
  <%= link_to "99Cats!", cats_path %>
</h1>
<small>
<% if logged_in? %>
  Logged in as <%= current_user.username %>
  <%= button_to "logout", session_path, method: :delete %>
<% else %>
  <%= link_to "sign in", new_session_path %>
  <%= link_to "sign up", new_user_path %>
<% end %>
</small>
<br>
<% if flash[:error] %>
  <p style='color: red;'><%= flash[:error] %></p>
<% end %>
<%= yield %>

</body>
</html>

solutions/w4/w4d3/cats99/app/views/users/new.html.erb
<h3>Sign Up</h3>

<% @user.errors.full_messages.each do |error| %>
  <p style='color: red;'><b><%= error %></b></p>
<% end %>

<%= form_for(@user) do %>
  <label for="user_username">username</label>
  <input type='text' name='user[username]' id='user_username' 
    value='<%= @user.username %>'>
  <br>
  <label for='user_password'>password</label>
  <input type='password' name='user[password]' id='user_password'>
  <br>
  <input type='submit'>
<% end %>